### ISSUE TITLE
Need "nuke all" option

### ISSUE THREAD

**Issue by zcopley** [rilakkyuma/tweetdelete#1]
Considering the current political environment, many people would like to just delete all of their Tweets from day one. I wasn't able to figure out how to do that and had to do it month-by-month. So, this is a feature request. Thank you for this great little utility.

**Comment by timmiehaha** [comment]
Thank you for your suggestion. I have added flags to the ```$ nuke``` command that allows both deletion of marked tweets with ```-m``` and complete deletion of all tweets (with a confirmation prompt) with ```-a```.
